security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Etudiant:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Etudiant
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\EtudiantAuthenticator

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
